### ISSUE TITLE
projection

### ISSUE THREAD

**Issue by tmarb3** [JooZef315/football-tracking-data-from-TV-broadcast#2]
I am able to get the tracking_df.

but I seem to be unable to plot the coordinates on a 2d image overlay. Is that possible with this repo?

**Comment by JooZef315** [comment]
Hi Thomas 

if I got your question right, and you are talking about the savaed df from **get_tracking_data** function and you want to plot the coordinates of 2d pitch -like in the readme-, I first want to say thanks for opening an Issue because you made me notice a minor mistake in readme file, that **get_tracking_data** function returns **tracked_frames**, **bboxes** while it returns **df_mapped**.
so you could manually modify it to return **tracked_frames**, **bboxes** if you like then we can use **visualize_mapping** function to plot on 2D pitch and the actual frame like in the readme file

However, the answer is still YES

the workflow you can use would be somthing like:

```python
from .mapping import get_frames_from_video
from .utils.visualization import visualize_mapping

frame_idx = any frame you want to plot

#two df you saved in Out/ normally
df = pd.read_csv(df_path)  
df_mapped= pd.read_csv(df_mappedpath)  

mapped_frames = get_frames_from_video(tracked_video_path) 
frame = mapped_frames[frame_idx - 1]

frame_init_df = df[df['frame'] == frame_idx]
frame_mapped_df = df_mapped[df_mapped['frame'] == test_frame_idx]

visualize_mapping(frame, frame_init_df, frame_mapped_df,  pitch_path  = './projection_2D/data/pitch_template.png', annotation = True)
```
I hope this answered your question, and if not please elaborate further
