### ISSUE TITLE
get_init_data Loop

### ISSUE THREAD

**Issue by Sgabox** [JooZef315/football-tracking-data-from-TV-broadcast#4]
Hi, i'm trying to use your library and as I lunch the function get_init_data it get stucked for too long. I'm trying to use it with a 10 minutes video of a match, the problem could be that i'm using a VM without GPU but it has 128 CPU so i should be covered, do you have any suggestions?

**Comment by JooZef315** [comment]
Hi,
Yes, I think if you use a VM with GPU the processing would take much less time.

and I have a **personal** suggestion, that to get the best of the tool, try use it with one or two sequent sequences of the game at time (10s to 1min for example) as the tool is not production ready yet as you might have noticed already (but it would of course process your video), and because I think longer videos often have time that the game is stopped at, throw-ins, etc.

**Comment by Sgabox** [comment]
Hi, thank you very much for your suggestions I'm gonna try your way
